package com.incomm.base24eps.ipm;

//jpos
import org.jpos.iso.*;


public class IPMISOPackager extends ISOBasePackager {
    private static final boolean pad = true;

    protected ISOFieldPackager field[] = {
        /*000*/ new IFA_NUMERIC (   4, "MESSAGE TYPE INDICATOR"),
        /*001*/ new IFB_BITMAP  (  16, "BIT MAP"),
        /*002*/ new IFA_LLNUM   (  16, "PAN - PRIMARY ACCOUNT NUMBER"),
        /*003*/ new IFA_NUMERIC (   6, "PROCESSING CODE"),
        /*004*/ new IFA_NUMERIC (  12, "AMOUNT, TRANSACTION"),
        /*005*/ new IFA_NUMERIC (  12, "AMOUNT, SETTLEMENT"),
        /*006*/ new IFA_NUMERIC (  12, "AMOUNT, CARDHOLDER BILLING"),
        /*007*/ new IF_CHAR     (  16, "TRANSMISSION DATE AND TIME"), //NOT PRESENT IN IPM
        /*008*/ new IFA_NUMERIC (   8, "AMOUNT, CARDHOLDER BILLING FEE"),//NOT PRESENT IN IPM
        /*009*/ new IFA_NUMERIC (   8, "CONVERSION RATE, SETTLEMENT"),
        /*010*/ new IFA_NUMERIC (   8, "CONVERSION RATE, CARDHOLDER BILLING"),
        /*011*/ new IFA_NUMERIC     (  12, "SYSTEM TRACE AUDIT NUMBER"),//NOT PRESENT IN IPM
        /*012*/ new IF_CHAR (  12, "TIME, LOCAL TRANSACTION"),
        /*013*/ new IF_CHAR (   8, "DATE, LOCAL TRANSACTION"),//NOT PRESENT IN IPM
        /*014*/ new IFA_NUMERIC (   4, "DATE, EXPIRATION"),
        /*015*/ new IFA_NUMERIC (   8, "DATE, SETTLEMENT"),//NOT PRESENT IN IPM
        /*016*/ new IFA_NUMERIC (   4, "DATE, CONVERSION"),//NOT PRESENT IN IPM
        /*017*/ new IFA_NUMERIC (   4, "DATE, CAPTURE"),//NOT PRESENT IN IPM
        /*018*/ new IFA_NUMERIC (   4, "MERCHANTS TYPE"),//NOT PRESENT IN IPM
        /*019*/ new IFA_NUMERIC (   3, "ACQUIRING INSTITUTION COUNTRY CODE"),//NOT PRESENT IN IPM
        /*020*/ new IFA_NUMERIC (   3, "PAN EXTENDED COUNTRY CODE"),//NOT PRESENT IN IPM
        /*021*/ new IFA_NUMERIC (   3, "FORWARDING INSTITUTION COUNTRY CODE"),//NOT PRESENT IN IPM
        /*022*/ new IFA_NUMERIC (   12, "POINT OF SERVICE ENTRY MODE"),
        /*023*/ new IFA_NUMERIC (   3, "CARD SEQUENCE NUMBER"),
        /*024*/ new IFA_NUMERIC (   3, "FUNCTION CODE"), //MODIFIED.
        /*025*/ new IFA_NUMERIC (   4, "MESSAGE REASON CODE"), //MODIFIED.
        /*026*/ new IFA_NUMERIC (   4, "CARD ACCEPTOR BUSINESS CODE"), //MODIFIED.
        /*027*/ new IFA_NUMERIC (   1, "AUTHORIZATION IDENTIFICATION RESP LEN"),//NOT PRESENT IN IPM
        /*028*/ new IFA_AMOUNT  (   9, "AMOUNT, TRANSACTION FEE"),//NOT PRESENT IN IPM
        /*029*/ new IFA_AMOUNT  (   9, "AMOUNT, SETTLEMENT FEE"),//NOT PRESENT IN IPM
        /*030*/ new IFA_AMOUNT  (   24, "AMOUNT, ORIGINAL"), //MODIFIED.
        /*031*/ new IFA_LLNUM  (   23, "ACQUIRER REFERENCE DATA"), //MODIFIED.
        /*032*/ new IFA_LLNUM   (  11, "ACQUIRING INSTITUTION IDENT CODE"),
        /*033*/ new IFA_LLNUM   (  11, "FORWARDING INSTITUTION IDENT CODE"),
        /*034*/ new IFA_LLCHAR  (  28, "PAN EXTENDED"),//NOT PRESENT IN IPM
        /*035*/ new IFA_LLNUM   (  37, "TRACK 2 DATA"),//NOT PRESENT IN IPM
        /*036*/ new IFA_LLLCHAR ( 104, "TRACK 3 DATA"),//NOT PRESENT IN IPM
        /*037*/ new IF_CHAR     (  12, "RETRIEVAL REFERENCE NUMBER"),
        /*038*/ new IF_CHAR (   6, "APPROVAL CODE"), //MODIFIED
        /*039*/ new IF_CHAR     (   2, "RESPONSE CODE"),//NOT PRESENT IN IPM
        /*040*/ new IF_CHAR     (   3, "SERVICE RESTRICTION CODE"),
        /*041*/ new IF_CHAR     (   8, "CARD ACCEPTOR TERMINAL IDENTIFICACION"),    //Different from ISO-8583 Specification
        /*042*/ new IF_CHAR     (  15, "CARD ACCEPTOR IDENTIFICATION CODE" ),
        /*043*/ new IFA_LLCHAR     (  99, "CARD ACCEPTOR NAME/LOCATION"),
        /*044*/ new IFA_LLCHAR  (  25, "ADITIONAL RESPONSE DATA"),//NOT PRESENT IN IPM
        /*045*/ new IFA_LLCHAR  (  76, "TRACK 1 DATA"),//NOT PRESENT IN IPM
        /*046*/ new IFA_LLLLCHAR(6000, "ADITIONAL DATA - ISO"),//NOT PRESENT IN IPM
        /*047*/ new IFA_LLLLCHAR(6000, "ADITIONAL DATA - NATIONAL"),//NOT PRESENT IN IPM
        /*048*/ new IFA_LLLCHAR(999, "ADITIONAL DATA - PRIVATE"),
        /*049*/ new IF_CHAR     (   3, "CURRENCY CODE, TRANSACTION"),
        /*050*/ new IF_CHAR     (   3, "CURRENCY CODE, SETTLEMENT"),
        /*051*/ new IF_CHAR     (   3, "CURRENCY CODE, CARDHOLDER BILLING"),
        /*052*/ new IFA_BINARY  (   8, "PIN DATA"   ),//NOT PRESENT IN IPM
        /*053*/ new IFA_NUMERIC (  16, "SECURITY RELATED CONTROL INFORMATION"),//NOT PRESENT IN IPM
        /*054*/ new IFA_LLLCHAR ( 20, "AMOUNTS ADDITIONAL"), //MODIFIED.
        /*055*/ new IFA_LLLCHAR ( 255, "RESERVED ISO"), //MODIFIED.
        /*056*/ new IFA_LLLCHAR ( 255, "RESERVED ISO"),//NOT PRESENT IN IPM
        /*057*/ new IFA_LLLCHAR ( 255, "RESERVED NATIONAL"),//NOT PRESENT IN IPM
        /*058*/ new IFA_LLLCHAR ( 255, "RESERVED NATIONAL"),//NOT PRESENT IN IPM
        /*059*/ new IFA_LLLCHAR ( 999, "NATIONAL POS GEOGRAPHIC DATA"),//NOT PRESENT IN IPM
        /*060*/ new IFA_NUMERIC (  12, "RESERVED PRIVATE"),//NOT PRESENT IN IPM
        /*061*/ new IFA_NUMERIC (  12, "RESERVED PRIVATE"),//NOT PRESENT IN IPM
        /*062*/ new IFA_LLLCHAR ( 999, "ADDITIONAL DATA 2"), //MODIFIED.
        /*063*/ new IFA_LLLCHAR ( 016, "SMS PRIVATE-USE FIELDS"),
        /*064*/ new IFA_BINARY  (   8, "MESSAGE AUTHENTICATION CODE FIELD"),//NOT PRESENT IN IPM
        /*065*/ new IFB_BINARY  (   1, "BITMAP, EXTENDED"),//NOT PRESENT IN IPM
        /*066*/ new IFA_NUMERIC (   1, "SETTLEMENT CODE"),//NOT PRESENT IN IPM
        /*067*/ new IFA_NUMERIC (   2, "EXTENDED PAYMENT CODE"),//NOT PRESENT IN IPM
        /*068*/ new IFA_NUMERIC (   3, "RECEIVING INSTITUTION COUNTRY CODE"),//NOT PRESENT IN IPM
        /*069*/ new IFA_NUMERIC (   3, "SETTLEMENT INSTITUTION COUNTRY CODE"),//NOT PRESENT IN IPM
        /*070*/ new IFA_NUMERIC (   3, "NETWORK MANAGEMENT INFORMATION CODE"),//NOT PRESENT IN IPM
        /*071*/ new IFA_NUMERIC (   8, "MESSAGE NUMBER"), //MODIFIED.
        /*072*/ new IFA_LLLCHAR ( 999, "DATA RECORD"), //MODIFIED.
        /*073*/ new IFA_NUMERIC (   6, "DATE ACTION"),
        /*074*/ new IFA_NUMERIC (  10, "CREDITS NUMBER"),//NOT PRESENT IN IPM
        /*075*/ new IFA_NUMERIC (  10, "CREDITS REVERSAL NUMBER"),//NOT PRESENT IN IPM
        /*076*/ new IFA_NUMERIC (  10, "DEBITS NUMBER"),//NOT PRESENT IN IPM
        /*077*/ new IFA_NUMERIC (  10, "DEBITS REVERSAL NUMBER"),//NOT PRESENT IN IPM
        /*078*/ new IFA_NUMERIC (  10, "TRANSFER NUMBER"),//NOT PRESENT IN IPM
        /*079*/ new IFA_NUMERIC (  10, "TRANSFER REVERSAL NUMBER"),//NOT PRESENT IN IPM
        /*080*/ new IFA_NUMERIC (  10, "INQUIRIES NUMBER"),//NOT PRESENT IN IPM
        /*081*/ new IFA_NUMERIC (  10, "AUTHORIZATION NUMBER"),//NOT PRESENT IN IPM
        /*082*/ new IFA_NUMERIC (  12, "CREDITS, PROCESSING FEE AMOUNT"),//NOT PRESENT IN IPM
        /*083*/ new IFA_NUMERIC (  12, "CREDITS, TRANSACTION FEE AMOUNT"),//NOT PRESENT IN IPM
        /*084*/ new IFA_NUMERIC (  12, "DEBITS, PROCESSING FEE AMOUNT"),//NOT PRESENT IN IPM
        /*085*/ new IFA_NUMERIC (  12, "DEBITS, TRANSACTION FEE AMOUNT"),//NOT PRESENT IN IPM
        /*086*/ new IFA_NUMERIC (  16, "CREDITS, AMOUNT"),//NOT PRESENT IN IPM
        /*087*/ new IFA_NUMERIC (  16, "CREDITS, REVERSAL AMOUNT"),//NOT PRESENT IN IPM
        /*088*/ new IFA_NUMERIC (  16, "DEBITS, AMOUNT"),//NOT PRESENT IN IPM
        /*089*/ new IFA_NUMERIC (  16, "DEBITS, REVERSAL AMOUNT"),//NOT PRESENT IN IPM
        /*090*/ new IFA_NUMERIC (  42, "ORIGINAL DATA ELEMENTS"),//NOT PRESENT IN IPM
        /*091*/ new IFA_NUMERIC (   1, "FILE UPDATE CODE"),//NOT PRESENT IN IPM
        /*092*/ new IFA_NUMERIC (   2, "FILE SECURITY CODE"),//NOT PRESENT IN IPM
        /*093*/ new IFA_LLNUM   (  11, "TXN DEST INST ID CODE"), //MODIFIED
        /*094*/ new IFA_LLNUM   (  11, "TXN ORG INST ID CODE"), //MODIFIED
        /*095*/ new IFA_LLNUM   (  10, "CARD ISSUER REF DATA"), //MODIFIED
        /*096*/ new IFA_NUMERIC (  8, "MESSAGE SECURITY CODE"),//NOT PRESENT IN IPM
        /*097*/ new IFA_NUMERIC (  16, "AMOUNT NET SETTLEMENT"),//NOT PRESENT IN IPM
        /*098*/ new IFA_NUMERIC (  25, "PAYEE"),//NOT PRESENT IN IPM
        /*099*/ new IFA_LLNUM   (  11, "SETTLEMENT INSTITUTION IDENTIFICATION CODE"),//NOT PRESENT IN IPM
        /*100*/ new IFA_LLNUM   (  11, "RECEIVING INSTITUTION IDENTIFICATION CODE"),
        
        /*101*/ new IFA_NUMERIC (  17, "FILE NAME"),//NOT PRESENT IN IPM
        /*102*/ new IFA_LLCHAR  (  28, "ACCOUNT IDENTIFICATION 1"),//NOT PRESENT IN IPM
        /*103*/ new IFA_LLCHAR  (  28, "ACCOUNT IDENTIFICATION 2"),//NOT PRESENT IN IPM
        /*104*/ new IFA_LLCHAR  ( 99, "TRANSACTION DESCRIPTION"),//NOT PRESENT IN IPM
		//Got these element descriptions from the internet. (http://wapedia.mobi/en/ISO_8583)
        /*105*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR ISO USE"),//NOT PRESENT IN IPM
        /*106*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR ISO USE"),//NOT PRESENT IN IPM
        /*107*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR ISO USE"),//NOT PRESENT IN IPM
        /*108*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR ISO USE"),//NOT PRESENT IN IPM
        /*109*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR ISO USE"),//NOT PRESENT IN IPM
        /*110*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR ISO USE"),//NOT PRESENT IN IPM
        
        /*111*/ new IFA_LLLNUM   (  12, "AMOUNT CURRENCY CONVERSION ASSESSMENT"),
        
        /*112*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR NATIONAL USE"),//NOT PRESENT IN IPM
        /*113*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR NATIONAL USE"),//NOT PRESENT IN IPM
        /*114*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR NATIONAL USE"),//NOT PRESENT IN IPM
        /*115*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR NATIONAL USE"),//NOT PRESENT IN IPM
        /*116*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR NATIONAL USE"),//NOT PRESENT IN IPM
        /*117*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR NATIONAL USE"),//NOT PRESENT IN IPM
        /*118*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR NATIONAL USE"),//NOT PRESENT IN IPM
        /*119*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR NATIONAL USE"),//NOT PRESENT IN IPM
        /*120*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR PRIVATE USE"),//NOT PRESENT IN IPM
        /*121*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR PRIVATE USE"),//NOT PRESENT IN IPM
        /*122*/ new IFA_LLLCHAR  ( 999, "RESERVED FOR PRIVATE USE"),//NOT PRESENT IN IPM
        
        /*123*/ new IFA_LLLCHAR   (  999, "ADDITIONAL DATA 3"),
        /*124*/ new IFA_LLLCHAR   (  999, "ADDITIONAL DATA 4"),
        /*125*/ new IFA_LLLCHAR   (  999, "ADDITIONAL DATA 5"),
        
        /*126*/ new IFA_LCHAR   (  6, "ISSUER TRACE ID"),//NOT PRESENT IN IPM
        
        /*127*/ new IFA_LLLCHAR   (  999, "RESERVED FOR PRIVATE USE"),

        /*128*/ new IFA_BINARY   (  16, "Message Authentication Code")//NOT PRESENT IN IPM
    };

    public IPMISOPackager() {
        super();
        setFieldPackager(field);
    }

}
